[package]
name = "bgmtv"
version = "0.1.0"
authors = ["duskmoon (Campbell He) <kp.campbell.he@duskmoon314.com>"]
edition = "2021"
repository = "https://github.com/duskmoon314/bgmtv-rs"
license = "MIT"
include = ["/src", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
reqwest = { version = "0.12.8", features = [
    "json",
    "native-tls",
    "native-tls-alpn",
] }
serde = { version = "1.0.210", features = ["derive"] }
serde_repr = "0.1.19"
thiserror = "1.0.64"
typed-builder = "0.20.0"

[dev-dependencies]
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tokio-test = "0.4.4"
